# Generated by Django 5.2.3 on 2025-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse_mail',
            field=models.EmailField(default='vide@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='prenom',
            field=models.CharField(default='kallel', max_length=100),
            preserve_default=False,
        ),
    ]
